CMS: {
    Login: [{
        icon: "Mushroom.png",
        english: "Gateway of Wind",
        name: "风之大陆",
        address: "159.75.223.31",
        port: "8484",
        interval: 5000,
        values: [],
        isMapleStoryGameServer: true,
        rel: "Login"
    },
    {
        icon: "Mushroom.png",
        english: "Gateway of Light",
        name: "光之大陆",
        address: "109.244.2.229",
        port: "8484",
        interval: 5000,
        values: [],
        isMapleStoryGameServer: true,
        rel: "Login"
    },
    {
        icon: "Mushroom.png",
        english: "Gateway of Clouds",
        name: "云之大陆",
        address: "109.244.2.214",
        port: "8484",
        interval: 5000,
        values: [],
        isMapleStoryGameServer: true,
        rel: "Login"
    },
    {
        icon: "Mushroom.png",
        english: "Gateway of Darkness",
        name: "暗之大陆",
        address: "109.244.2.219",
        port: "8484",
        interval: 5000,
        values: [],
        isMapleStoryGameServer: true,
        rel: "Login"
    },
    {
        icon: "Mushroom.png",
        english: "Gateway of Water",
        name: "水之大陆",
        address: "159.75.223.108",
        port: "8484",
        interval: 5000,
        values: [],
        isMapleStoryGameServer: true,
        rel: "Login"
    },
    {
        icon: "Mushroom.png",
        english: "Tespia",
        name: "测试区",
        address: "116.211.24.140",
        port: "8484",
        interval: 5000,
        values: [],
        isMapleStoryGameServer: true,
        rel: "Login"
    }
    ],
    '路西德': [
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 1",
            address: "159.75.223.83",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 2",
            address: "159.75.223.84",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 3 贵宾",
            address: "159.75.223.85",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 4 贵宾",
            address: "159.75.223.86",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 5",
            address: "159.75.223.87",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 6",
            address: "159.75.223.88",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 7",
            address: "159.75.223.89",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 8",
            address: "159.75.223.90",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 9",
            address: "159.75.223.91",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 10",
            address: "159.75.223.92",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 11",
            address: "159.75.223.93",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 12",
            address: "159.75.223.94",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 13",
            address: "159.75.223.95",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 14",
            address: "159.75.223.96",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 15",
            address: "159.75.223.97",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 16",
            address: "159.75.223.98",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 17",
            address: "159.75.223.99",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 18",
            address: "159.75.223.100",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 19",
            address: "159.75.223.101",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "频道 20",
            address: "159.75.223.102",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "商城",
            address: "159.75.223.37",
            port: "8700",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        },
        {
            icon: "Lucid.png",
            english: "Lucid",
            name: "拍卖场",
            address: "159.75.223.23",
            port: "8795",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "路西德"
        }
    ],
    '威尔': [
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 1",
            address: "159.75.223.62",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 2",
            address: "159.75.223.63",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 3 贵宾",
            address: "159.75.223.64",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 4 贵宾",
            address: "159.75.223.65",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 5",
            address: "159.75.223.66",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 6",
            address: "159.75.223.67",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 7",
            address: "159.75.223.68",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 8",
            address: "159.75.223.69",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 9",
            address: "159.75.223.70",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 10",
            address: "159.75.223.71",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 11",
            address: "159.75.223.72",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 12",
            address: "159.75.223.73",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 13",
            address: "159.75.223.74",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 14",
            address: "159.75.223.75",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 15",
            address: "159.75.223.76",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 16",
            address: "159.75.223.77",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 17",
            address: "159.75.223.78",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 18",
            address: "159.75.223.79",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 19",
            address: "159.75.223.80",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "频道 20",
            address: "159.75.223.81",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "商城",
            address: "159.75.223.38",
            port: "8701",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        },
        {
            icon: "Will.png",
            english: "Will",
            name: "拍卖场",
            address: "159.75.223.23",
            port: "8796",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "威尔"
        }
    ],
    '奥尔卡': [
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 1",
            address: "159.75.223.41",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 2",
            address: "159.75.223.42",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 3 贵宾",
            address: "159.75.223.43",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 4 贵宾",
            address: "159.75.223.44",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 5",
            address: "159.75.223.45",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 6",
            address: "159.75.223.46",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 7",
            address: "159.75.223.47",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 8",
            address: "159.75.223.48",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 9",
            address: "159.75.223.49",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 10",
            address: "159.75.223.50",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 11",
            address: "159.75.223.51",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 12",
            address: "159.75.223.52",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 13",
            address: "159.75.223.53",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 14",
            address: "159.75.223.54",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 15",
            address: "159.75.223.55",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 16",
            address: "159.75.223.56",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 17",
            address: "159.75.223.57",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 18",
            address: "159.75.223.58",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 19",
            address: "159.75.223.59",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "频道 20",
            address: "159.75.223.60",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "商城",
            address: "159.75.223.39",
            port: "8702",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        },
        {
            icon: "Orchid_CN.png",
            english: "Orchid",
            name: "拍卖场",
            address: "159.75.223.23",
            port: "8797",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "奥尔卡"
        }
    ],
    '戴米安': [
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 1",
            address: "109.244.2.233",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 2",
            address: "109.244.2.234",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 3 贵宾",
            address: "109.244.2.235",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 4 贵宾",
            address: "109.244.2.236",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 5",
            address: "109.244.2.237",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 6",
            address: "109.244.2.238",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 7",
            address: "109.244.2.239",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 8",
            address: "109.244.2.240",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 9",
            address: "109.244.2.241",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 10",
            address: "109.244.2.242",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 11",
            address: "109.244.2.243",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 12",
            address: "109.244.2.244",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 13",
            address: "109.244.2.245",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 14",
            address: "109.244.2.246",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 15",
            address: "109.244.2.247",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 16",
            address: "109.244.2.248",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 17",
            address: "109.244.2.249",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 18",
            address: "109.244.2.250",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 19",
            address: "109.244.2.251",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "频道 20",
            address: "109.244.2.252",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "商城",
            address: "109.244.2.232",
            port: "8730",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        },
        {
            icon: "Damien.png",
            english: "Damien",
            name: "拍卖场",
            address: "109.244.2.159",
            port: "8795",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "戴米安"
        }
    ],
    '希拉': [
        {
            icon: "Hilla.png",
            name: "频道 1",
            address: "109.244.2.187",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "希拉"
        },
        {
            icon: "Hilla.png",
            name: "频道 2",
            address: "109.244.2.193",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "希拉"
        },
        {
            icon: "Hilla.png",
            name: "频道 3 贵宾",
            address: "109.244.2.188",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "希拉"
        },
        {
            icon: "Hilla.png",
            name: "频道 4 贵宾",
            address: "109.244.2.188",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "希拉"
        },
        {
            icon: "Hilla.png",
            name: "频道 5",
            address: "109.244.2.189",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "希拉"
        },
        {
            icon: "Hilla.png",
            name: "频道 6",
            address: "109.244.2.194",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "希拉"
        },
        {
            icon: "Hilla.png",
            name: "频道 7",
            address: "109.244.2.190",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "希拉"
        },
        {
            icon: "Hilla.png",
            name: "频道 8",
            address: "109.244.2.190",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "希拉"
        },
        {
            icon: "Hilla.png",
            name: "频道 9",
            address: "109.244.2.191",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "希拉"
        },
        {
            icon: "Hilla.png",
            name: "频道 10",
            address: "109.244.2.191",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "希拉"
        },
        {
            icon: "Hilla.png",
            name: "频道 11",
            address: "109.244.2.192",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "希拉"
        },
        {
            icon: "Hilla.png",
            name: "频道 12",
            address: "109.244.2.192",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "希拉"
        },
        {
            icon: "Hilla.png",
            name: "商城",
            address: "109.244.2.208",
            port: "8760",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "希拉"
        },
        {
            icon: "Hilla.png",
            name: "拍卖场",
            address: "109.244.2.206",
            port: "8795",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "希拉"
        }
    ],
    '班·雷昂': [
        {
            icon: "VonLeon.png",
            english: "VonLeon",
            name: "频道 1",
            address: "109.244.2.198",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "班·雷昂"
        },
        {
            icon: "VonLeon.png",
            english: "VonLeon",
            name: "频道 2",
            address: "109.244.2.198",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "班·雷昂"
        },
        {
            icon: "VonLeon.png",
            english: "VonLeon",
            name: "频道 3",
            address: "109.244.2.199",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "班·雷昂"
        },
        {
            icon: "VonLeon.png",
            english: "VonLeon",
            name: "频道 4",
            address: "109.244.2.199",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "班·雷昂"
        },
        {
            icon: "VonLeon.png",
            english: "VonLeon",
            name: "频道 5",
            address: "109.244.2.200",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "班·雷昂"
        },
        {
            icon: "VonLeon.png",
            english: "VonLeon",
            name: "频道 6",
            address: "109.244.2.200",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "班·雷昂"
        },
        {
            icon: "VonLeon.png",
            english: "VonLeon",
            name: "频道 7",
            address: "109.244.2.201",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "班·雷昂"
        },
        {
            icon: "VonLeon.png",
            english: "VonLeon",
            name: "频道 8",
            address: "109.244.2.201",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "班·雷昂"
        },
        {
            icon: "VonLeon.png",
            english: "VonLeon",
            name: "频道 9",
            address: "109.244.2.202",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "班·雷昂"
        },
        {
            icon: "VonLeon.png",
            english: "VonLeon",
            name: "频道 10",
            address: "109.244.2.202",
            port: "8586",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "班·雷昂"
        },
        {
            icon: "VonLeon.png",
            english: "VonLeon",
            name: "商城",
            address: "109.244.2.209",
            port: "8790",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "班·雷昂"
        },
        {
            icon: "VonLeon.png",
            english: "VonLeon",
            name: "拍卖场",
            address: "109.244.2.207",
            port: "8795",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "班·雷昂"
        }
    ],
    '麦格纳斯': [
        {
            icon: "Magnus.png",
            english: "Magnus",
            name: "频道 1",
            address: "159.75.223.22",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "麦格纳斯"
        },
        {
            icon: "Magnus.png",
            english: "Magnus",
            name: "频道 2",
            address: "159.75.223.115",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "麦格纳斯"
        },
        {
            icon: "Magnus.png",
            english: "Magnus",
            name: "频道 3 贵宾",
            address: "159.75.223.116",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "麦格纳斯"
        },
        {
            icon: "Magnus.png",
            english: "Magnus",
            name: "频道 4 贵宾",
            address: "159.75.223.117",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "麦格纳斯"
        },
        {
            icon: "Magnus.png",
            english: "Magnus",
            name: "频道 5",
            address: "159.75.223.118",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "麦格纳斯"
        },
        {
            icon: "Magnus.png",
            english: "Magnus",
            name: "频道 6",
            address: "159.75.223.119",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "麦格纳斯"
        },
        {
            icon: "Magnus.png",
            english: "Magnus",
            name: "频道 7",
            address: "159.75.223.120",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "麦格纳斯"
        },
        {
            icon: "Magnus.png",
            english: "Magnus",
            name: "频道 8",
            address: "159.75.223.121",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "麦格纳斯"
        },
        {
            icon: "Magnus.png",
            english: "Magnus",
            name: "频道 9",
            address: "159.75.223.122",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "麦格纳斯"
        },
        {
            icon: "Magnus.png",
            english: "Magnus",
            name: "频道 10",
            address: "159.75.223.123",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "麦格纳斯"
        },
        {
            icon: "Magnus.png",
            english: "Magnus",
            name: "频道 11",
            address: "159.75.223.124",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "麦格纳斯"
        },
        {
            icon: "Magnus.png",
            english: "Magnus",
            name: "频道 12",
            address: "159.75.223.125",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "麦格纳斯"
        },
        {
            icon: "Magnus.png",
            english: "Magnus",
            name: "商城",
            address: "159.75.223.113",
            port: "7120",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "麦格纳斯"
        },
        {
            icon: "Magnus.png",
            english: "Magnus",
            name: "拍卖场 House",
            address: "159.75.223.103",
            port: "8795",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "麦格纳斯"
        }
    ],
    '测试区': [
        {
            icon: "TestWorld.png",
            english: "TestWorld",
            name: "频道 1",
            address: "116.211.24.51",
            port: "8584",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "测试区"
        },
        {
            icon: "TestWorld.png",
            english: "TestWorld",
            name: "频道 2",
            address: "116.211.24.51",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "测试区"
        },
        {
            icon: "TestWorld.png",
            english: "TestWorld",
            name: "频道 3",
            address: "116.211.24.110",
            port: "8584",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "测试区"
        },
        {
            icon: "TestWorld.png",
            english: "TestWorld",
            name: "频道 4",
            address: "116.211.24.110",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "测试区"
        },
        {
            icon: "TestWorld.png",
            english: "TestWorld",
            name: "频道 5",
            address: "116.211.24.134",
            port: "8584",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "测试区"
        },
        {
            icon: "TestWorld.png",
            english: "TestWorld",
            name: "频道 6",
            address: "116.211.24.134",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "测试区"
        },
        {
            icon: "TestWorld.png",
            english: "TestWorld",
            name: "频道 7",
            address: "116.211.24.135",
            port: "8584",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "测试区"
        },
        {
            icon: "TestWorld.png",
            english: "TestWorld",
            name: "频道 8",
            address: "116.211.24.135",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "测试区"
        },
        {
            icon: "TestWorld.png",
            english: "TestWorld",
            name: "频道 9",
            address: "116.211.24.136",
            port: "8584",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "测试区"
        },
        {
            icon: "TestWorld.png",
            english: "TestWorld",
            name: "频道 10",
            address: "116.211.24.136",
            port: "8585",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "测试区"
        },
        {
            icon: "TestWorld.png",
            english: "TestWorld",
            name: "商城",
            address: "116.211.24.140",
            port: "8700",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "测试区"
        },
        {
            icon: "TestWorld.png",
            english: "TestWorld",
            name: "拍卖场 House",
            address: "116.211.11.211",
            port: "8795",
            interval: 5000,
            values: [],
            isMapleStoryGameServer: true,
            rel: "测试区"
        }
    ]
},
